name: build-api

on:
  push:
    branches:
      - main
    paths:
      - 'DockerCourseApi/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Spin up database
      run: docker-compose up -d database

    - name: Seed database
      run: |
        chmod +x ./Database/wait-and-run.sh
        docker compose run --build database-seed

    - name: Build  
      run: |
        docker build /
        -t $${{ secrets.DOCKER_USERNAME }}/api:latest \
        -t $${{ secrets.DOCKER_USERNAME }}/api:${{github.run_number}} \
        -f ./DockerCourseApi/Dockerfile \
        --network host \
        ./DockerCourseApi/.
    
    - name: Push
      run: |
        docker push $${{ secrets.DOCKER_USERNAME }}/api:latest
        docker push $${{ secrets.DOCKER_USERNAME }}/api:${{github.run_number}}

    - name: Tear down database
      if: always()
      run: docker compose down database